name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Publish

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21 and cache Gradle dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Artifacts
        if: github.event_name == 'push'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: ./gradlew publish
